// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUtmG4Cro1LfTGTGXBf6C0a4vBIVHGJe4',
    appId: '1:515242522703:web:291f6f0b273f3d0f65123a',
    messagingSenderId: '515242522703',
    projectId: 'omniyaapp-736a9',
    authDomain: 'omniyaapp-736a9.firebaseapp.com',
    storageBucket: 'omniyaapp-736a9.firebasestorage.app',
    measurementId: 'G-9GTJV4RZ4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyS3hfUPdRSIbeOr1eIPWU34zsmV6V1Pw',
    appId: '1:515242522703:android:4f838914b7a36ecc65123a',
    messagingSenderId: '515242522703',
    projectId: 'omniyaapp-736a9',
    storageBucket: 'omniyaapp-736a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAArvycStHBJ97hMb54WQLdXC6AYdOLM1M',
    appId: '1:515242522703:ios:5493b53497c6bc5665123a',
    messagingSenderId: '515242522703',
    projectId: 'omniyaapp-736a9',
    storageBucket: 'omniyaapp-736a9.firebasestorage.app',
    iosBundleId: 'com.example.omniya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAArvycStHBJ97hMb54WQLdXC6AYdOLM1M',
    appId: '1:515242522703:ios:5493b53497c6bc5665123a',
    messagingSenderId: '515242522703',
    projectId: 'omniyaapp-736a9',
    storageBucket: 'omniyaapp-736a9.firebasestorage.app',
    iosBundleId: 'com.example.omniya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUtmG4Cro1LfTGTGXBf6C0a4vBIVHGJe4',
    appId: '1:515242522703:web:2d69cbf6f87cb63665123a',
    messagingSenderId: '515242522703',
    projectId: 'omniyaapp-736a9',
    authDomain: 'omniyaapp-736a9.firebaseapp.com',
    storageBucket: 'omniyaapp-736a9.firebasestorage.app',
    measurementId: 'G-YXW566MB80',
  );
}
